export const FETCH_PRODUCTS = 'fetch_products'
export const SHOW_MODAL = 'show_modal'
export const HIDE_MODAL = 'hide_modal'
export const ADD_TO_CART = 'add_to_cart'
export const REMOVE_FROM_CART = 'remove_from_cart'
export const EMPTY_CART = 'empty_cart'
export const HANDLE_TOKEN = 'handle_token'
